name: Deploy Easypanel

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # IMPORTANTE: Mude o nome do repositório abaixo para cada projeto novo
          tags: suportereipcp/saas:latest
          # Injeção de variáveis de ambiente no build.
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_TLDRAW_LICENSE_KEY=${{ secrets.NEXT_PUBLIC_TLDRAW_LICENSE_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_DB_SCHEMA=${{ secrets.NEXT_PUBLIC_DB_SCHEMA }}

  trigger-easypanel:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Easypanel
        # O link do webhook deve estar cadastrado nos Secrets do GitHub:
        run: curl -X POST "${{ secrets.EASYPANEL_WEBHOOK_URL }}"
